-- 1. 레시피 마스터 테이블 (Canonical Source - 1:1 with Video URL)
CREATE TABLE IF NOT EXISTS recipes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  title TEXT NOT NULL,
  summary TEXT,
  ingredients JSONB, -- 구조화된 재료 데이터 (List[Ingredient])
  steps JSONB,       -- 구조화된 조리 과정 (List[RecipeStep])
  flavor JSONB,      -- 맛 분석 데이터
  tip TEXT,          -- 셰프의 원본 팁
  video_url TEXT UNIQUE,
  video_id TEXT UNIQUE  -- 유튜브 비디오 고유 ID (캐시 키)
);

-- 2. 사용자 테이블 (Supabase Auth 연동 고려)
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  nickname TEXT,
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- 3. 카테고리 테이블
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  description TEXT
);

-- 4. 레시피-카테고리 관계 테이블
CREATE TABLE IF NOT EXISTS recipe_categories (
  recipe_id BIGINT REFERENCES recipes(id) ON DELETE CASCADE,
  category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
  PRIMARY KEY (recipe_id, category_id)
);

-- 5. 사용자 레시피 보관함 (Personalization Core)
-- 단순 북마크를 넘어, 사용자별 커스텀 팁과 조절 기록을 저장
CREATE TABLE IF NOT EXISTS user_collections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  recipe_id BIGINT REFERENCES recipes(id) ON DELETE CASCADE,
  custom_tip TEXT,              -- "내 입맛엔 고춧가루 빼는게 좋음" 등 개인화 메모 or AI 제안
  ingredient_adjustments JSONB, -- {"excluded": ["고춧가루"], "scale": 0.8}
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  UNIQUE(user_id, recipe_id)
);

-- 6. 요리 기록 (Cooking Logs)
CREATE TABLE IF NOT EXISTS cooking_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  recipe_id BIGINT REFERENCES recipes(id) ON DELETE CASCADE,
  notes TEXT,       -- "이번엔 좀 짰다" 등의 피드백
  image_url TEXT,   -- 내가 만든 요리 사진
  cooked_date TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- 7. AI 분석 로그
CREATE TABLE IF NOT EXISTS analysis_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_url TEXT NOT NULL,
  raw_response JSONB,
  processing_time_ms INTEGER,
  success BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Optional: Enable RLS and policies if needed
-- alter table recipes enable row level security;
-- create policy "Public Access" on recipes for all using (true);
