-- 003_tag_system.sql
-- 레시피북 태그 & 아카이빙 시스템 (Phase 1)
-- 설계 문서: @docs/collection_tag_system.md

-- ==========================================================
-- 1. user_collections 테이블 컬럼 추가
-- ==========================================================
ALTER TABLE user_collections
  ADD COLUMN IF NOT EXISTS is_favorite       BOOLEAN   DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS my_rating         SMALLINT  CHECK (my_rating BETWEEN 1 AND 5),
  ADD COLUMN IF NOT EXISTS cooked_count      INTEGER   DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_cooked_at    TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS category_override TEXT;

COMMENT ON COLUMN user_collections.is_favorite       IS '즐겨찾기 여부';
COMMENT ON COLUMN user_collections.my_rating         IS '내 별점 (1-5, NULL=미평가)';
COMMENT ON COLUMN user_collections.cooked_count      IS '만들어본 횟수';
COMMENT ON COLUMN user_collections.last_cooked_at    IS '마지막 요리 일시';
COMMENT ON COLUMN user_collections.category_override IS 'AI 자동 분류를 유저가 수정한 경우 덮어쓰기 (NULL이면 recipes.category 사용)';

-- ==========================================================
-- 2. collection_tags 테이블 (유저 태그 마스터)
-- ==========================================================
CREATE TABLE IF NOT EXISTS collection_tags (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    UUID   REFERENCES users(id) ON DELETE CASCADE,
  name       TEXT   NOT NULL,
  color      TEXT   NOT NULL DEFAULT '#e8ddd4',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, name)
);

COMMENT ON TABLE  collection_tags       IS '유저별 커스텀 태그 마스터';
COMMENT ON COLUMN collection_tags.color IS '태그 색상 (hex). 기본 8색: #f28b82, #fbbc04, #34a853, #4285f4, #a8c7fa, #e6c9a8, #d3d3d3, #e8ddd4';

-- ==========================================================
-- 3. collection_tag_items 테이블 (컬렉션-태그 연결)
-- ==========================================================
CREATE TABLE IF NOT EXISTS collection_tag_items (
  collection_id BIGINT REFERENCES user_collections(id) ON DELETE CASCADE,
  tag_id        BIGINT REFERENCES collection_tags(id)  ON DELETE CASCADE,
  PRIMARY KEY (collection_id, tag_id)
);

COMMENT ON TABLE collection_tag_items IS '보관함 레시피와 유저 태그의 다대다 연결';

-- ==========================================================
-- 4. 인덱스
-- ==========================================================

-- 즐겨찾기 필터 (유저별 즐겨찾기 목록 조회)
CREATE INDEX IF NOT EXISTS idx_collections_favorite
  ON user_collections (user_id, is_favorite)
  WHERE is_favorite = TRUE;

-- 별점 필터/정렬
CREATE INDEX IF NOT EXISTS idx_collections_rating
  ON user_collections (user_id, my_rating)
  WHERE my_rating IS NOT NULL;

-- 최근 요리 정렬
CREATE INDEX IF NOT EXISTS idx_collections_last_cooked
  ON user_collections (user_id, last_cooked_at DESC NULLS LAST);

-- 태그 조회 (유저별 태그 목록)
CREATE INDEX IF NOT EXISTS idx_tags_user
  ON collection_tags (user_id);

-- 태그 아이템 역방향 조회 (특정 태그에 연결된 레시피들)
CREATE INDEX IF NOT EXISTS idx_tag_items_tag
  ON collection_tag_items (tag_id);

-- 카테고리 오버라이드 필터
CREATE INDEX IF NOT EXISTS idx_collections_category
  ON user_collections (user_id, category_override);
